language: ruby
sudo: required
services:
  - docker
before_install:
  - docker pull peterhuene/puppetcpp
script:
  - docker run -v `pwd`:/puppetcpp peterhuene/puppetcpp /bin/sh -c "cd /puppetcpp && cmake . && make -j 2 && bin/puppetcpp --help && ctest -V"
